name: ML Pipeline CI

on:
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest great_expectations pandas scikit-learn flake8 black mypy pytest-cov
        pip install mlflow numpy tensorflow
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Lint with flake8
      run: |
        flake8 day5/演習3 --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 day5/演習3 --count --exit-zero --max-complexity=10 --max-line-length=88 --statistics

    - name: Format check with black
      run: |
        black --check day5/演習3

    - name: Run data tests
      run: |
        export PYTHONPATH="${PYTHONPATH}:$(pwd)"
        pytest day5/演習3/tests/test_data.py -v

    - name: Run model tests
      run: |
        export PYTHONPATH="${PYTHONPATH}:$(pwd)"
        pytest day5/演習3/tests/test_model.py -v

    - name: Run model inference tests
      run: |
        export PYTHONPATH="${PYTHONPATH}:$(pwd)"
        pytest day5/演習3/tests/test_model_inference.py -v
        pytest day5/演習3/tests/test_model_inference.py -v --disable-warnings
